// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PriceIt.Data.DbContexts;

namespace PriceIt.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PriceIt.Core.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<string>("ProductImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ProductUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Website")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LastUpdate = new DateTime(2021, 6, 10, 9, 41, 51, 556, DateTimeKind.Local).AddTicks(8283),
                            Name = "TestProduct1",
                            Price = 60.99f,
                            ProductImageUrl = "https://assets.mmsrg.com/isr/166325/c1/-/ASSET_MMS_72715345/fee_786_587_png",
                            ProductUrl = "https://www.saturn.de/de/product/_cooler-master-masterwatt-lite-700w-230v-2602309.html",
                            Website = 0
                        },
                        new
                        {
                            Id = 2,
                            LastUpdate = new DateTime(2021, 6, 10, 9, 41, 51, 559, DateTimeKind.Local).AddTicks(7110),
                            Name = "TestProduct2",
                            Price = 60.99f,
                            ProductImageUrl = "https://assets.mmsrg.com/isr/166325/c1/-/ASSET_MMS_72796414/fee_786_587_png",
                            ProductUrl = "https://www.saturn.de/de/product/_seasonic-core-gc-650-gold-2625115.html",
                            Website = 0
                        },
                        new
                        {
                            Id = 3,
                            LastUpdate = new DateTime(2021, 6, 10, 9, 41, 51, 559, DateTimeKind.Local).AddTicks(7157),
                            Name = "TestProduct3",
                            Price = 60.99f,
                            ProductImageUrl = "https://assets.mmsrg.com/isr/166325/c1/-/pixelboxx-mss-80864028/fee_786_587_png",
                            ProductUrl = "https://www.saturn.de/de/product/_be-quiet-pure-power-11-500w-2505555.html",
                            Website = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
